[zsh] er: add .tar.zst and .zst (zstd compression algorithm)

diff --git a/zsh_functions/er b/zsh_functions/er
--- a/zsh_functions/er
+++ b/zsh_functions/er
@@ -3,18 +3,20 @@ er() {
   for f in "$@" ; do
     if [[ -f $f ]] ; then
       case "$f" in
-        *.tar)             tar xf "$f"     ;;
         *.rar|*.cbr)       unrar x "$f"    ;;
         *.zip|*.cbz|*.jar) unzip "$f"      ;;
+        *.gz)              gunzip "$f"     ;;
+        *.tar.zst)         tar --zstd -xf "$f" ;;
+        *.zst)             unzstd "$f"     ;;
+        *.tar)             tar xf "$f"     ;;
         *.tar.bz2|*.tbz2)  tar xjf "$f"    ;;
         *.tar.gz|*.tgz)    tar xzf "$f"    ;;
         *.tar.xz)          tar xJf "$f"    ;;
         *.bz2)             bunzip2 "$f"    ;;
-        *.gz)              gunzip "$f"     ;;
         *.Z)               uncompress "$f" ;;
         *.7z)              7z x "$f"       ;;
         *.deb) /usr/bin/ar vx "$f" ;; #&& tar -xzvf data.tar.gz ;;
-        *)     echo "$0: '$f' cannot be extracted via extract()" >&2 ; return 2;;
+        *) echo "$0: '$f' cannot be extracted via extract()" >&2 ; return 2;;
       esac
     else
       echo "$0: '$f' is not a valid file" >&2 ; return 1
